- hosts: all
  become: yes
  gather_facts: false
  tasks:
    - name: Set up the stable repository
      remote_user: ubuntu
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present
        update_cache: yes

    - name: Install docker
      remote_user: ubuntu
      apt:
        name: docker-ce
        state: present
        update_cache: ye

    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
